# Generated by Django 3.1.4 on 2020-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_auto_20201214_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
